### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by molmorg** [hiediutley/HelloPhoneGap1.0#2]
Your project doesn't build for me - get three errors:

/Users/molmorg/Documents/Projects/HelloPhoneGap1.0/HelloPhoneGap1/Plugins/iPod/iPodCommand.m:136:6: error: 'iPodCommand' cannot use 'super' because it is a root class [3]

/Users/molmorg/Documents/Projects/HelloPhoneGap1.0/HelloPhoneGap1/Plugins/ActivityIndicator/ActivityIndicatorCommand.h:15:39:{15:1-15:36}: error: cannot find interface declaration for 'PGPlugin', superclass of 'ActivityIndicatorCommand' [3]

/Users/molmorg/Documents/Projects/HelloPhoneGap1.0/HelloPhoneGap1/Plugins/iPod/iPodCommand.h:18:26:{18:1-18:23}: error: cannot find interface declaration for 'PGPlugin', superclass of 'iPodCommand' [3]

Help! Many of us using PhoneGap aren't hardcore Xcode(rs) - it comes with the territory!

**Comment by bevand** [comment]
It appears the PhoneGap import is incorrect on the iPodCommand.h and ActivityIndicatorCommand.h

Try replacing:

```
#ifdef PHONEGAP_FRAMEWORK
#import <PhoneGap/PhoneGapDelegate.h>
#else
#import "PhoneGapDelegate.h"
#endif
```

with:

```
#ifdef PHONEGAP_FRAMEWORK
    #import <PhoneGap/PGPlugin.h>
#else
    #import "PGPlugin.h"
#endif
```

**Comment by hiediutley** [comment]
I fixed this...
